### ISSUE TITLE
ERROR: failed to solve: process /bin/sh -c python3 diarize.py -a /home/transcriptionstream/test.wav did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by zalpany2000** [transcriptionstream/transcriptionstream#11]
when I was to build the docker images locally, I encountered this error: 

```
 => ERROR [16/17] RUN python3 diarize.py -a /home/transcriptionstream/test.wav                                                                                         12.6s
------
 > [16/17] RUN python3 diarize.py -a /home/transcriptionstream/test.wav:
6.664 /usr/local/lib/python3.10/dist-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
6.664   torchaudio.set_audio_backend("soundfile")
7.095 torchvision is not available - cannot save figures
11.17 Traceback (most recent call last):
11.17   File "/whisper-diarization/diarize.py", line 21, in <module>
11.17     from ctc_forced_aligner import (
11.17 ImportError: cannot import name 'load_alignment_model' from 'ctc_forced_aligner' (unknown location)
------
Dockerfile:59
--------------------
  57 |     
  58 |     # Run the necessary scripts so we have our transcription models IN the image. Adds to build time for download.
  59 | >>> RUN python3 diarize.py -a /home/transcriptionstream/test.wav
  60 |     RUN whisperx --model large-v3 --language en /home/transcriptionstream/test.wav --compute_type int8
  61 |     #RUN python3 -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/torch/whisperx-vad-segmentation.bin
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 diarize.py -a /home/transcriptionstream/test.wav" did not complete successfully: exit code: 1

```

any suggestion ?

**Comment by transcriptionstream** [comment]
I've updated the ts-gpu Dockerfile to resolve the issue. Please get a fresh clone and install again. You can always use start-nobuild.sh to pull the prebuilt images if needed.

**Comment by zalpany2000** [comment]
Thanks alot, that helped fixing this issue, now I got this error: curl: (7) Failed to connect to localhost port 11434 after 0 ms: Connection refused
`transcriptionstream
Starting services with docker-compose...
./start-nobuild.sh: line 21: docker-compose: command not found
Downloading  mistral model
curl: (7) Failed to connect to localhost port 11434 after 0 ms: Connection refused
Re-attaching to console logs
./start-nobuild.sh: line 30: docker-compose: command not found
`

**Comment by transcriptionstream** [comment]
not sure what exactly is going on with your setup, maybe a docker-compose version or permissions error? Try removing the images and recreating. I've just built from the latest version and run the no build version without issue.

**Comment by zalpany2000** [comment]
thanks for the guidance, fresh VM with newer docker and docker compose helped. 

just realized that I have to have GPU on the machine to run it. is there any way to run it without GPU ?

**Comment by transcriptionstream** [comment]
this should run with cpu only, but it won't be fast or all that fun
