### ISSUE TITLE
Great work, but I have some questions to consult.

### ISSUE THREAD

**Issue by yue001** [transcriptionstream/transcriptionstream#12]
1: Is it necessary to upload two files (transcribe & diarize) for ts-web to run as showing in ts-web walkthrough video(https://www.youtube.com/watch?v=pbZ8o7_MjG4 )?
2: What are the transcribe & diarize files? Do they have to be in mp3 format? Are there any restrictions on size or duration of the audio files?
3: Does it support audio in other languages? For example: Chinese.
4: I would greatly appreciate it if you could provide me with the transcribe & diarize audio files used in the example https://www.youtube.com/watch?v=pbZ8o7_MjG4 .

Thinks.

**Comment by transcriptionstream** [comment]
Greetings yue001,

1 - transcribe and diarize are separate processes
2 - mp3, wav, ogg, flac. Please see /ts-gpu/diarize_example_d.sh. File size is dependent on batch size and available memory
3 - you can set the language in /ts-gpu/transcribe_example_d.sh
4 - please feel free to test with your own audio samples

**Comment by yue001** [comment]
> Greetings yue001,
> 
> 1 - transcribe and diarize are separate processes 2 - mp3, wav, ogg, flac. Please see /ts-gpu/diarize_example_d.sh. File size is dependent on batch size and available memory 3 - you can set the language in /ts-gpu/transcribe_example_d.sh 4 - please feel free to test with your own audio samples

Thank you for the reply. I am still confused about the two audio files needed for transcribe & diarize. I don't know the difference between the two files. Can I use the same meeting recorded audio file for both processes?

Also, I couldn't find the /ts-gpu/diarize_example_d.sh file in the project. Did I misunderstand something?
