### ISSUE TITLE
Always restarting

### ISSUE THREAD

**Issue by juliusmlr** [transcriptionstream/transcriptionstream#16]
Hi, 

i'm realy happy to found this repo! In theory it could help me a lot. 

Unfortunately i have some trouble with the ts-gpu service, which is restarting all the time. 
Do you know what i could do here? 

Thanks and best regards
<img width="833" alt="Terminal" src="https://github.com/transcriptionstream/transcriptionstream/assets/89013161/c521301e-a788-4314-9b29-36ca9fdaeb3e">

**Comment by transcriptionstream** [comment]
greetings @juliusmlr - what you are seeing is just noisy logging and is expected. Please upload an audio file via web/ssh and you will see the diarization begin

**Comment by juliusmlr** [comment]
Thank you so much! It's working!
Is there any way i could get the original transcription language instead of the translation?

**Comment by transcriptionstream** [comment]
I've not looked at how that process works. If it's doable it would be making changes to the configuration files in the whisper-diarization repository which you are free to clone and try!
