### ISSUE TITLE
Compatibility with Colab or Kaggle?

### ISSUE THREAD

**Issue by NicholasTheGreat** [transcriptionstream/transcriptionstream#2]
Hi, your demo look really interesting. I was just wondering if this would be compatible with a colab or kaggle notebook? It would be very helpful as often you can use a Tesla T4 16gb for free.

**Comment by transcriptionstream** [comment]
Greetings Nicholas! Appreciate the kind words. It may be compatible but I'm not familiar using either colab or kaggle.
