### ISSUE TITLE
Improve diarization

### ISSUE THREAD

**Issue by Saphar** [transcriptionstream/transcriptionstream#5]
Hello,

I have some meeting recordings that I would like to transcribe and diarize. Unfortunately the bare install doesn't do very well. Is there a way to improve this? What should I look for ?

**Comment by transcriptionstream** [comment]
Can you explain a little more as to what isn't working well?

**Comment by Saphar** [comment]
Sorry for the late response I was doing some experiments with other frameworks to understand a little bit better.

I ended up just writing a simple web interface with Gradio, then diarizing the audio with pyannote. Then I tried to group all the segments into speakers, break up the audio into multiple speakers and transcribing each audio file separately. This way I have the transcription in a grouped format based on the speakers.

But I really like how you built this app, I wish I could run the same with the code I wrote.
