### ISSUE TITLE
Meilisearch functionality

### ISSUE THREAD

**Issue by Saphar** [transcriptionstream/transcriptionstream#7]
Hello,

I am not able to have a stable working Meilisearch. At first it showed in the logs that I need to restart Meilisearch with a Master Key, which I did. Then I entered the same master key in the index-single.py but it always gives a response that it was not successfull. Even though the document that is added to the index looks right. 

Here is the log:
```
ts-meilisearch              | 2024-03-15T16:20:09.150794Z  INFO HTTP request{method=GET host="172.30.1.12:7700" route=/ query_parameters= user_agent=python-requests/2.31.0 status_code=200}: meilisearch: close time.busy=28.3µs time.idle=143µs
ts-meilisearch              | 2024-03-15T16:20:09.165457Z  INFO HTTP request{method=POST host="172.30.1.12:7700" route=/indexes/transcriptions/documents query_parameters= user_agent=Meilisearch Python (v0.31.0) status_code=202}: meilisearch: close time.busy=599µs time.idle=11.3ms
ts-meilisearch              | 2024-03-15T16:20:09.170094Z  INFO index_scheduler: A batch of tasks was successfully completed with 0 successful tasks and 1 failed tasks.
```

Any ideas what could be wrong? How should we use this feature?

**Comment by transcriptionstream** [comment]
I'll take a look this weekend and see if I can replicate the issue

**Comment by transcriptionstream** [comment]
I built a fresh copy of transcription stream from the public git repo and the meilisearch indexing works out of the box. 
`ts-meilisearch              | 2024-03-24T20:22:58.033360Z  INFO HTTP request{method=GET host="172.30.1.12:7700" route=/ query_parameters= user_agent=python-requests/2.31.0 status_code=200}: meilisearch: close time.busy=1.67ms time.idle=2.75ms
ts-meilisearch              | 2024-03-24T20:22:58.070709Z  INFO HTTP request{method=POST host="172.30.1.12:7700" route=/indexes/transcriptions/documents query_parameters= user_agent=Meilisearch Python (v0.31.0) status_code=202}: meilisearch: close time.busy=8.36ms time.idle=25.4ms
ts-meilisearch              | 2024-03-24T20:22:58.091913Z  INFO milli::update::index_documents::enrich: Primary key was not specified in index. Inferred to 'id'
ts-gpu                      | API endpoint is running.
ts-meilisearch              | 2024-03-24T20:22:58.115704Z  INFO index_scheduler::batch: document indexing done indexing_result=DocumentAdditionResult { indexed_documents: 2, number_of_documents: 1 }
ts-gpu                      | Creating summary.txt for battleofwits.txt in /transcriptionstream/transcribed/battleofwits_20240324202059
ts-meilisearch              | 2024-03-24T20:22:58.132257Z  INFO index_scheduler: A batch of tasks was successfully completed with 1 successful tasks and 0 failed tasks.`

My guess is that the meilisearch key needs to be updated elsewhere in your instance. I'll drop a list of locations.

**Comment by transcriptionstream** [comment]
I've added meili_master_key to the .env to help simplify the setup. Will update the repo with that and a few other updates later today.

**Comment by transcriptionstream** [comment]
Please pull and build the latest version, utilizing the .env file for the meilisearch master key, and let me know if your issue is resolved.
