### ISSUE TITLE
$'\r': command not found

### ISSUE THREAD

**Issue by J-Pheeze** [transcriptionstream/transcriptionstream#8]
I am using dockerdesktop. And I am fairly new to containers so I am not sure if this is an issue with my setup. However, when I run the container I get the following as a repeating error every 5 seconds.

2024-03-28 00:41:16 ts-gpu          | /root/scripts/ts-control.sh: line 7: $'\r': command not found
2024-03-28 00:41:16 ts-gpu          | /root/scripts/ts-control.sh: line 11: $'\r': command not found
2024-03-28 00:41:16 ts-gpu          | /root/scripts/ts-control.sh: line 14: $'\r': command not found
2024-03-28 00:41:16 ts-gpu          | /root/scripts/ts-control.sh: line 17: $'\r': command not found
2024-03-28 00:41:16 ts-gpu          | /root/scripts/ts-control.sh: line 19: syntax error near unexpected token `$'{\r''
'024-03-28 00:41:16 ts-gpu          | /root/scripts/ts-control.sh: line 19: `start_process_if_allowed() {

**Comment by J-Pheeze** [comment]
Hello, I am using windows 10 and I have an nvidia RTX 3070ti.

**Comment by transcriptionstream** [comment]
Looks like a line return issue between linux and windows. You'll need to convert the line returns in the script is ts-gpu prior to building the image

**Comment by transcriptionstream** [comment]
Any update? If you're still having issues, pull the latest version and give the recently added [start-nobuid.sh](https://github.com/transcriptionstream/transcriptionstream/blob/main/start-nobuild.sh) script to pull prebuilt images from docker hub.

**Comment by J-Pheeze** [comment]
I pulled the newest and have use notepad++ to update the line endings. After trying to change the line ends I got a new error "/root/scripts/ts-control.sh: line 28: [: 0: unary operator expected".

**Comment by transcriptionstream** [comment]
You’re going to need to either use Linux or try using the windows Linux subsystem to run the start-nobuild.sh script

**Comment by J-Pheeze** [comment]
ok awesome I got it to do a transcription on a 5 minute clip. however when it tries to make a summary it give the error "FileNotFoundError: [Errno 2] No such file or directory: '/transcriptionstream/transcribed/FILE_NAME_20240406033936/summary.txt'
2024-04-05 23:42:52 Traceback (most recent call last):
2024-04-05 23:42:52   File "/root/scripts/ts-summarize.py", line 106, in <module>
2024-04-05 23:42:52     print("Error message from API:", json_data.get('error', ''))
2024-04-05 23:42:52 NameError: name 'json_data' is not defined
2024-04-05 23:42:52 Traceback (most recent call last):
2024-04-05 23:42:52   File "/root/scripts/auto-summary.py", line 41, in <module>
2024-04-05 23:42:52     scan_and_summarize('/transcriptionstream/transcribed')
2024-04-05 23:42:52   File "/root/scripts/auto-summary.py", line 38, in scan_and_summarize
2024-04-05 23:42:52     os.chown(summary_file, uid, gid)

**Comment by transcriptionstream** [comment]
Please be sure you’ve pulled the latest commit from both GitHub and docker hub.

**Comment by J-Pheeze** [comment]
dockerhub commands return that I have the lasted and I fully removed and recloned from Github

**Comment by transcriptionstream** [comment]
the error you're getting indicates you may not have the new transcriptionstream/transcriptionstream ollama model pulled - can you verify the new model has been pulled by start-nobuild.sh?

**Comment by J-Pheeze** [comment]
is there a command i can run or other way to check?

**Comment by J-Pheeze** [comment]
I realized that one thing that may be causing issues was that my username had a space in it. Which can throw off linux systems. I made a new user and I get a proper summary and diarized transcription out of my recording. It works well for my 5 minute recording, but the 30 minute recording uploads, gets broken into 5 segments, and seems to be processed but the transcription never appears in dropdown or the transcribed folder

**Comment by transcriptionstream** [comment]
Any error or messages in the docker logs? Does the transcription exist in the /home/transcriptionstream/transcribed folder when connecting with sftp? The process may be running your video card out of vram and crashing.

**Comment by J-Pheeze** [comment]
the mp3 is in the transcriptionstream/transcribed folder but no .txt or .srt

checking through the logs these are the messages that mention issues
ts-gpu          | torchvision is not available - cannot save figures

ts-gpu          | [NeMo W 2024-04-11 05:52:22 transformer_bpe_models:59] Could not import NeMo NLP collection which is required for speech translation model.

ts-gpu          | Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.

ts-gpu          | Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu117. Bad things might happen unless you revert torch to 1.x.

ts-gpu          | RuntimeError: CUDA failed with error out of memory

so the out of memory one seems the most serious. Is there anything I can do about it to make it run slower but not overload my memory? Or do i just have to do my transcriptions in smaller chunks?

**Comment by transcriptionstream** [comment]
you can modify the /ts-gpu/transcribe_example_d.sh script to bring the batch size down to help on the memory front

Line 46
                python3 diarize_parallel.py --batch-size 16 --whisper-model $DIARIZATION_MODEL --language en -a "$audio_file"

set the batch size to something like 8 and rebuild the ts-gpu image

**Comment by J-Pheeze** [comment]
Ok great, that got me up to an hour long transcription. at 1.5 hours I'm not seeing any new errors except

ts-gpu          | Killed
ts-gpu          | WARNING:root:Source splitting failed, using original audio file. Use --no-stem argument to disable it. 

But it continues after that and seems to freeze up after it does " [5/5] extract embedding 100%". It just reverts to doing the repeating

ts-web          | 172.30.0.1 - - [13/Apr/2024 05:31:06] "GET /check_alert HTTP/1.1" 200 -
ts-web          | 172.30.0.1 - - [13/Apr/2024 05:31:11] "GET /check_alert HTTP/1.1" 200 -
ts-gpu          | Starting new instance of auto-summary.py. Current count: 0
ts-web          | 172.30.0.1 - - [13/Apr/2024 05:31:16] "GET /check_alert HTTP/1.1" 200 -
ts-web          | 172.30.0.1 - - [13/Apr/2024 05:31:21] "GET /check_alert HTTP/1.1" 200 -
ts-web          | 172.30.0.1 - - [13/Apr/2024 05:31:26] "GET /check_alert HTTP/1.1" 200 -
ts-gpu          | Starting new instance of auto-summary.py. Current count: 0
ts-web          | 172.30.0.1 - - [13/Apr/2024 05:31:31] "GET /check_alert HTTP/1.1" 200 -

**Comment by transcriptionstream** [comment]
It still sounds like you’re running into a memory issue - you can try lowering the batch size more, but more memory is going to be the ultimate solution. You may want to open an issue with https://github.com/MahmoudAshraf97/whisper-diarization the project code that is actually performing the diarization.
